# Generated by Django 4.2.9 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
    ]
